### ISSUE TITLE
请问什么时候能支持iOS的广点通/优量汇呢?

### ISSUE THREAD

**Issue by BadReese** [gstory0404/flutter_universalad#2]
如题,谢谢

**Comment by gstory0404** [comment]
正在处理，由于优量汇sdk需要swift转接，插件中使用有问题，在找解决方案。如果有解决方案可以联系我🌝🌝

**Comment by cdk8s-zelda** [comment]
找了一圈，还是你靠谱，鼓励一下！！！

**Comment by BadReese** [comment]
等iOS支持了可以通知下~ @gstory0404

**Comment by BytesZero** [comment]
@BadReese @cdk8s-zelda 
我使用的这个[flutter_qq_ads](https://github.com/FlutterAds/flutter_qq_ads)插件，非常不错，支持 Android、iOS

[
![image](https://user-images.githubusercontent.com/8764899/144745067-dc519c79-c343-4ba0-8148-433f65f52b5a.png)](https://github.com/FlutterAds/flutter_qq_ads)

**Comment by gstory0404** [comment]
已支持穿山甲、优量汇android、ios双端所有广告

**Comment by cdk8s-zelda** [comment]
> @BadReese @cdk8s-zelda
> 我使用的这个[flutter_qq_ads](https://github.com/FlutterAds/flutter_qq_ads) 插件，非常不错，支持 Android、iOS
> [ ![image](https://user-images.githubusercontent.com/8764899/131288138-c54de4cd-6f2f-4833-b16c-0f4a3b007836.png) ](https://github.com/FlutterAds/flutter_qq_ads)

感谢！！！
两位都是 Flutter Ad 中的顶流！！！
