### ISSUE TITLE
正常加载，监听激励广告的信息没有

### ISSUE THREAD

**Issue by tzt1994** [gstory0404/flutter_universalad#4]

**Comment by tzt1994** [comment]
按照文档写的
<img width="403" alt="WechatIMG863" src="https://user-images.githubusercontent.com/15625580/136366857-026a42c8-ff21-408f-a864-b1ad148eeeaa.png">
![Uploading WechatIMG865.png…]()

**Comment by tzt1994** [comment]
flutter版本2.5.1

**Comment by tzt1994** [comment]
<img width="909" alt="WechatIMG865" src="https://user-images.githubusercontent.com/15625580/136367183-e142cdfc-abc2-47a5-a8f9-c8f780d3abf6.png">

**Comment by gstory0404** [comment]
激励广告 播放正常，服务器校验异常 查看服务器验证的配置
