### ISSUE TITLE
1.0.12版本激励视频有bug，onRewardArrived回调没有暴露出来，插件内部Null check operator used on a null value

### ISSUE THREAD

**Issue by zjpjohn** [gstory0404/flutter_universalad#6]
onRewardArrived: true amount:0 name:Bundle[{reward_extra_key_error_code=0, reward_extra_key_reward_name=100金币, reward_extra_key_reward_propose=1.0, reward_extra_key_error_msg=null, reward_extra_key_reward_amount=100}]
I/flutter ( 7380): 1 观看激励视频广告成功 transId= verify=true amount=100 name=100金币
E/flutter ( 7380): [ERROR:flutter/lib/ui/ui_dart_state.cc(209)] Unhandled Exception: Null check operator used on a null value
E/flutter ( 7380): #0      FlutterUnionadStream.initAdStream.<anonymous closure> (package:flutter_unionad/flutter_unionad_stream.dart:129:62)
E/flutter ( 7380): #1      _rootRunUnary (dart:async/zone.dart:1436:47)

**Comment by gstory0404** [comment]
聚合插件暂不支持onRewardArrived阶段奖励回调，仅支持onVerify完整奖励回调
